# rubocop:disable Naming/FileName
# rubocop:enable Naming/FileName
require 'jekyll'
require 'mini_magick'
require_relative 'jekyll/favicon'
require_relative 'jekyll/favicon/hooks'
require_relative 'jekyll/favicon/icon'
require_relative 'jekyll/favicon/generator'
require_relative 'jekyll/favicon/metadata'
require_relative 'jekyll/favicon/tag'
require_relative 'jekyll/favicon/utils/browserconfig'
require_relative 'jekyll/favicon/utils/image'
require_relative 'jekyll/favicon/utils/resource'
require_relative 'jekyll/favicon/utils/taggable'
require_relative 'jekyll/favicon/utils/taggables/link'
require_relative 'jekyll/favicon/utils/taggables/meta'
require_relative 'jekyll/favicon/utils/webmanifest'
require_relative 'jekyll/favicon/version'
